### ISSUE TITLE
MaxMind::DB::Writer 0.300002 fails to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by onyphe** [maxmind/MaxMind-DB-Writer-perl#95]
Hello,

We find an issue on the compilation of the module as described below.
Note: the previous version compiles successfully.

Building and testing MaxMind-DB-Writer-0.300002 ... FAIL
! Installing MaxMind::DB::Writer failed. See /root/.cpanm/work/1530095179.266502/build.log for details. Retry with --force to force install it.

less /root/.cpanm/work/1530095179.266502/build.log

In file included from c/tree.h:3:0,
                 from c/tree.c:1:
c/tree.c: In function ‘insert_network’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first
 use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^

Regards,

**Comment by nchelluri** [comment]
Hi onyphe, I have reproduced the problem on a fresh Ubuntu 18.04 VM.

I will confer with my colleagues who are more experienced with this area and we will get back to you. Thanks for the report!

**Comment by amitdrucker** [comment]
Happens for me too.
running on Centos7

**Comment by amitdrucker** [comment]
@onyphe - You can workaround the issue by building previous version 0.300001
(untar previous version and run cpan . from that folder)

**Comment by oalders** [comment]
I'm seeing the same on a fresh Ubuntu 17.10 VM.

**Comment by onyphe** [comment]
@amitdrucker thanks for the workaround, that is what we do until there is a definitive fix.

**Comment by onyphe** [comment]
It works now. Thank you for your work,
